debug: true
logger:
  level: debug

vcode:
  appCode: ""
  appKey: ""
  appSecret: ""

yuemiao:
  # tk需要自行抓包获取到,在约苗小程序里，随便一个接口获取header中的tk填写此处
  tk: ""
  # 用来表示是否输出详细日志
  verbose: true
  # 切记时间格式必须按照如下填写，请勿修改
  start_time: "2020-07-31 13:59:20"
  # 需要抢购的门诊id
  seckill_id: "10916"
  # 打针的人的id，注意不是userId
  linkman_id: "王小娅"
  # 打针的人的身份证
  id_card_no: "500243199609210025"

  ################## 如下V2版本不再需要，但是保留代码和配置
  # 抢购疫苗的省份，注意要写全称，默认:四川省
  province: "四川省"
  # 抢购疫苗的城市，注意要写全称，默认:成都市
  city: "成都市"
  # 抢购疫苗的区县，注意要写全称，默认:空字符串，可以不写
  district: "锦江区"
  # 1:进口二价  2:进口四价  3:进口九价   还有其他的，后续再加上来
  vaccines: "3"
  # 抢购的门诊全称 "成都市锦江区莲新社区卫生服务中心"
  # 如果不知道是哪个门诊，可以点进约苗公众号中，看到秒杀的疫苗的门诊填入即可，一定要填写全称，不能有错别字或者少字的情况，因为是按照严格字符串对等匹配的
  department_name: "成都高新锦欣艾嘉综合门诊部"
  ################## 如上V2版本不再需要，但是保留代码和配置

jinniu:
  # 抢购的时间开始点，若修改，请将时间修改为准确时间前几秒时间即可，比如网上预约的开始时间为 2020-07-03 16:31:00，则这里时间为 2020-07-03 16:30:55
  # 切记时间格式必须按照如下填写，请勿修改
  start_time: "2021-10-25 08:29:59"
  # 抓包获取
  his_id: 10916
  # 抓包获取
  platform_source: 1
  # 抓包获取
  platform_id: 10916
  # 用来表示是否输出详细日志
  verbose: true
  # 抓包获取
  cookie: "Cookie: UM_distinctid=17ca60a2131722-0dd974e5448ad7-61203a26-144000-17ca60a2132779; CNZZDATA1261985103=1917387668-1634868016-https%253A%252F%252Fopen.weixin.qq.com%252F%7C1634868016; _xxhm_=%7B%22id%22%3A21477501%2C%22mobile%22%3A%2218661155238%22%2C%22nickName%22%3A%22%E9%AB%98%E5%86%B7%E4%BD%8E%E8%83%BD%E5%84%BF%22%2C%22headerImg%22%3A%22http%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2Fic9BcyRDyOIsnAbwgquoIrYMuCPibWZg8ap7nQqwzeiaMCIKTVGaQee6LsNYJ0OARkzZUthiaiahe2Bo8YQzjFI61blfeD4kTDaUG%2F132%22%2C%22regionCode%22%3A%22510106%22%2C%22name%22%3A%22%E7%8E%8B**%22%2C%22uFrom%22%3A%22depa_vacc_detail%22%2C%22wxSubscribed%22%3A1%2C%22birthday%22%3A%221996-09-21+02%3A00%3A00%22%2C%22sex%22%3A2%2C%22hasPassword%22%3Afalse%2C%22birthdayStr%22%3A%221996-09-21%22%7D; _xzkj_=wxtoken:0bf2771309c7e0142fc25f62dcd5ae70_57979c8bd5475b0f6d7fa9dbc5050017"
